# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
        -   id: destroyed-symlinks
        # -   id: end-of-file-fixer
        -   id: check-added-large-files
            args: ['--maxkb=5120']
        -   id: check-case-conflict
        -   id: check-executables-have-shebangs
        -   id: check-shebang-scripts-are-executable
        -   id: check-merge-conflict
        -   id: detect-private-key
        # -   id: check-json
        -   id: check-toml
        -   id: check-yaml

# -   repo: https://github.com/codingjoe/relint
#     rev: 1.2.1
#     hooks:
#         - id: relint

# -   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
#     rev: v1.2.2
#     hooks:
#     -   id: python-safety-dependencies-check

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
        - id: isort
          name: isort (python)

# because our vscode config likes comments
# FIXME: make apply only to things we specifically know it should apply to
- repo: https://gitlab.com/bmares/check-json5
  rev: v1.0.0
  hooks:
  - id: check-json5

